import { NextRequest } from "next/server";
import { PDFDocument, StandardFonts, rgb, PageSizes } from "pdf-lib";
import { getSession, requireRole } from "@/lib/auth";
import { buildUserRows, EXPORT_COLUMNS } from "@/lib/exportRows";
import { ActivityLog } from "@/models/ActivityLog";

const PAGE_WIDTH = PageSizes.A3[1]; // landscape A3 width
const PAGE_HEIGHT = PageSizes.A3[0];
const MARGIN = 28;

export async function GET(req: NextRequest) {
  const s = await getSession();
  const guard = requireRole(s, ["admin", "super_admin"]);
  if (guard) return guard;
  const { searchParams } = new URL(req.url);
  const filters = {
    q: searchParams.get("q") || undefined,
    status: searchParams.get("status") || undefined,
    role: searchParams.get("role") || undefined,
    gender: searchParams.get("gender") || undefined
  };
  const rows = await buildUserRows(filters);

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  // Pick a tight subset of columns for PDF readability (still includes the most important fields).
  const COLS = [
    { key: "recordId", label: "Record" },
    { key: "fullName", label: "Full name" },
    { key: "email", label: "Email" },
    { key: "role", label: "Role" },
    { key: "status", label: "Status" },
    { key: "active", label: "Active" },
    { key: "company", label: "Company" },
    { key: "department", label: "Dept." },
    { key: "currentTraining", label: "Training" },
    { key: "trainingCode", label: "Code" },
    { key: "enrollmentStatus", label: "Enroll" },
    { key: "progressPercent", label: "%" },
    { key: "lastLogin", label: "Last login" }
  ];

  const colWidths = [60, 120, 150, 60, 55, 45, 90, 80, 130, 70, 65, 35, 70];
  const totalW = colWidths.reduce((a, b) => a + b, 0);
  const startX = MARGIN;
  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawHeader(page, bold, font, rows.length, filters);
  let y = PAGE_HEIGHT - 110;

  drawTableHeader(page, bold, COLS.map(c => c.label), colWidths, startX, y);
  y -= 22;

  const rowH = 18;

  rows.forEach((r, i) => {
    if (y < MARGIN + rowH) {
      drawFooter(page, font, pdf.getPageCount());
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      drawHeader(page, bold, font, rows.length, filters);
      y = PAGE_HEIGHT - 110;
      drawTableHeader(page, bold, COLS.map(c => c.label), colWidths, startX, y);
      y -= 22;
    }
    if (i % 2 === 0) {
      page.drawRectangle({ x: startX, y: y - 4, width: totalW, height: rowH, color: rgb(0.97, 0.97, 0.99) });
    }
    let x = startX;
    COLS.forEach((c, idx) => {
      const text = String((r as any)[c.key] ?? "");
      page.drawText(truncate(text, colWidths[idx] - 4, font, 9), { x: x + 4, y: y + 1, size: 9, font, color: rgb(0.12, 0.16, 0.24) });
      x += colWidths[idx];
    });
    y -= rowH;
  });
  drawFooter(page, font, pdf.getPageCount());

  const bytes = await pdf.save();
  await ActivityLog.create({ actor: s!.sub, actorRole: s!.role, action: "export_pdf", target: "users", metadata: { count: rows.length, filters } });
  const fileName = `advancia-users-${new Date().toISOString().slice(0, 10)}.pdf`;
  return new Response(bytes, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${fileName}"`
    }
  });
}

function drawHeader(page: any, bold: any, font: any, count: number, filters: any) {
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 70, width: PAGE_WIDTH, height: 70, color: rgb(0.92, 0.45, 0.07) });
  page.drawText("ADVANCIA Trainings — Users report", { x: MARGIN, y: PAGE_HEIGHT - 38, size: 20, font: bold, color: rgb(1, 1, 1) });
  page.drawText(new Date().toLocaleString(), { x: PAGE_WIDTH - 220, y: PAGE_HEIGHT - 38, size: 11, font, color: rgb(1, 1, 1) });
  const filterText = `Filters: ${stringifyFilters(filters)} • ${count} records`;
  page.drawText(filterText, { x: MARGIN, y: PAGE_HEIGHT - 88, size: 10, font, color: rgb(0.3, 0.34, 0.44) });
}
function stringifyFilters(f: any) {
  const k = Object.entries(f).filter(([, v]) => v).map(([k, v]) => `${k}=${v}`);
  return k.length ? k.join(" · ") : "none";
}
function drawTableHeader(page: any, bold: any, labels: string[], widths: number[], startX: number, y: number) {
  page.drawRectangle({ x: startX, y: y - 4, width: widths.reduce((a, b) => a + b, 0), height: 22, color: rgb(0.13, 0.16, 0.24) });
  let x = startX;
  labels.forEach((l, i) => {
    page.drawText(l, { x: x + 4, y: y + 4, size: 10, font: bold, color: rgb(1, 1, 1) });
    x += widths[i];
  });
}
function drawFooter(page: any, font: any, n: number) {
  page.drawText(`Generated by ADVANCIA Trainings — page ${n}`, { x: MARGIN, y: 14, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
}
function truncate(text: string, maxWidth: number, font: any, size: number) {
  let s = text;
  while (font.widthOfTextAtSize(s, size) > maxWidth - 2 && s.length > 1) s = s.slice(0, -2) + "…";
  return s;
}
